const data = window.AUDIT_DATA;
const money = n => new Intl.NumberFormat('en-US',{style:'currency',currency:'CNY',notation:'compact',maximumFractionDigits:1}).format(n);
const number = n => new Intl.NumberFormat('en-US').format(n);
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));

function renderKPIs(){
  const k=data.kpis;
  const cards=[['Transactions tested',number(k.transactions_analyzed),'Revenue population',''],['Revenue analyzed',money(k.total_revenue),'FY2025 recognized value',''],['High-risk revenue',number(k.high_risk_transactions),`${money(k.high_risk_revenue)} flagged`,'risk'],['Journals tested',number(k.journal_entries_analyzed),'Complete GL population',''],['Unusual journals',number(k.unusual_journal_entries),'Prioritized for review','danger']];
  document.querySelector('#kpis').innerHTML=cards.map(x=>`<div class="kpi ${x[3]}"><label>${x[0]}</label><b>${x[1]}</b><small>${x[2]}</small></div>`).join('');
  document.querySelector('#revenue-kpis').innerHTML=[['Risk threshold',money(k.high_value_threshold),'Population-derived 98th percentile'],['High-risk items',number(k.high_risk_transactions),'Score ≥ 35'],['Recommended samples','60','42 targeted · 18 random']].map(x=>`<div class="kpi"><label>${x[0]}</label><b>${x[1]}</b><small>${x[2]}</small></div>`).join('');
  document.querySelector('#flagged-count').textContent=number(k.high_risk_transactions+k.unusual_journal_entries);
}
function lineChart(){
  const rows=data.monthly_revenue,w=760,h=230,p=30,max=Math.max(...rows.map(x=>x.revenue))*1.1,x=i=>p+i*(w-2*p)/(rows.length-1),y=v=>h-p-v*(h-2*p)/max;
  const area=rows.map((r,i)=>`${i?'L':'M'}${x(i)},${y(r.revenue)}`).join(' ')+` L${x(rows.length-1)},${h-p} L${x(0)},${h-p} Z`;
  const path=rows.map((r,i)=>`${i?'L':'M'}${x(i)},${y(r.revenue)}`).join(' ');
  const flagged=rows.map((r,i)=>`<circle cx="${x(i)}" cy="${y(r.revenue)}" r="${Math.max(2,Math.min(8,r.high_risk_revenue/r.revenue*80))}" fill="#d89122"><title>${r.month}: ${money(r.high_risk_revenue)} high risk</title></circle>`).join('');
  document.querySelector('#revenue-chart').innerHTML=`<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="Monthly revenue trend"><defs><linearGradient id="g" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#52b788" stop-opacity=".28"/><stop offset="1" stop-color="#52b788" stop-opacity=".02"/></linearGradient></defs>${[.25,.5,.75,1].map(v=>`<line x1="${p}" x2="${w-p}" y1="${y(max*v)}" y2="${y(max*v)}" stroke="#e5e9e3"/><text x="0" y="${y(max*v)+3}">${money(max*v)}</text>`).join('')}<path d="${area}" fill="url(#g)"/><path d="${path}" fill="none" stroke="#0f624b" stroke-width="2.5"/>${flagged}${rows.map((r,i)=>`<text x="${x(i)}" y="${h-5}" text-anchor="middle">${r.month.slice(5)}</text>`).join('')}</svg>`;
}
function donuts(){
  const html=['revenue','journals'].map(key=>{const d=data.risk_distribution[key],total=Object.values(d).reduce((a,b)=>a+b,0),high=(d.High||0)/total*100,mid=(d.Medium||0)/total*100;return `<div class="donut-wrap"><div class="donut" style="position:relative;background:conic-gradient(var(--red) 0 ${high}%,var(--amber) ${high}% ${high+mid}%,#dfe9e3 ${high+mid}% 100%)"><b>${(high).toFixed(1)}%</b></div><span>${key==='revenue'?'Revenue':'Journals'} · high risk</span></div>`}).join('');
  document.querySelector('#risk-donuts').innerHTML=html;
}
function bars(id,rows){const max=Math.max(...rows.map(x=>x.count));document.querySelector(id).innerHTML=rows.slice(0,7).map(x=>`<div class="bar-row"><span>${esc(x.reason)}</span><div class="bar-track"><div class="bar-fill" style="width:${x.count/max*100}%"></div></div><b>${number(x.count)}</b></div>`).join('')}
function revenueTable(rows=data.top_revenue){document.querySelector('#revenue-table').innerHTML=rows.map(r=>`<tr><td><strong>${esc(r.transaction_id)}</strong></td><td>${esc(r.customer_name)}</td><td>${esc(r.invoice_date)}</td><td class="amount">${money(+r.amount)}</td><td><span class="risk-pill ${r.risk_level.toLowerCase()}">${r.risk_score}</span></td><td>${esc(r.risk_reasons)}</td><td>${esc(r.suggested_procedure)}</td></tr>`).join('')}
function journalTable(){document.querySelector('#journal-table').innerHTML=data.top_journals.map(r=>`<tr><td><strong>${esc(r.journal_id)}</strong></td><td>${esc(r.posting_datetime.slice(0,16).replace('T',' '))}</td><td>${esc(r.debit_account)}<br><span style="color:#8a958f">to ${esc(r.credit_account)}</span></td><td class="amount">${money(+r.amount)}</td><td><span class="risk-pill ${r.risk_level.toLowerCase()}">${r.risk_score}</span></td><td>${esc(r.risk_reasons)}</td></tr>`).join('')}
function benford(){const rows=data.benford,w=380,h=310,p=35,max=.34,bw=(w-2*p)/rows.length;document.querySelector('#benford-chart').innerHTML=`<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="Benford observed and expected distributions">${[.1,.2,.3].map(v=>`<line x1="${p}" x2="${w-p}" y1="${h-p-v/max*(h-2*p)}" y2="${h-p-v/max*(h-2*p)}" stroke="#e5e9e3"/><text x="5" y="${h-p-v/max*(h-2*p)+3}">${Math.round(v*100)}%</text>`).join('')}${rows.map((r,i)=>{let x=p+i*bw,y=h-p-r.observed/max*(h-2*p),ey=h-p-r.expected/max*(h-2*p);return `<rect x="${x+4}" y="${y}" width="${bw-8}" height="${h-p-y}" fill="#52b788" rx="2"><title>Observed ${(r.observed*100).toFixed(1)}%</title></rect><circle cx="${x+bw/2}" cy="${ey}" r="3" fill="#d89122"/><text x="${x+bw/2}" y="${h-12}" text-anchor="middle">${r.digit}</text>`}).join('')}</svg>`}

const titles={overview:['Engagement overview','Aurora Industrial Automation Co. · FY2025'],revenue:['Revenue analytics','Full-population revenue recognition testing'],journals:['Journal entry testing','Management override and unusual posting analysis'],sampling:['Audit sampling','Evidence-led sample recommendation']};
document.querySelectorAll('.nav-item').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.nav-item,.view').forEach(x=>x.classList.remove('active'));btn.classList.add('active');document.querySelector(`#${btn.dataset.view}`).classList.add('active');document.querySelector('#page-title').textContent=titles[btn.dataset.view][0];document.querySelector('#page-subtitle').textContent=titles[btn.dataset.view][1]}));
document.querySelector('#revenue-search').addEventListener('input',e=>{const q=e.target.value.toLowerCase();revenueTable(data.top_revenue.filter(r=>`${r.transaction_id} ${r.customer_name}`.toLowerCase().includes(q)))});
document.querySelector('#export-btn').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='audit-findings-summary.json';a.click();URL.revokeObjectURL(a.href)});
renderKPIs();lineChart();donuts();bars('#revenue-reasons',data.revenue_reasons);bars('#journal-reasons',data.journal_reasons);revenueTable();journalTable();benford();
